spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://172.17.0.3:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: XnRthUd5iPAKM70hgLlVA437Qtc05tN2NO7NGm3ZsFQzWIJGBR1mAB/2ON7s2xMVlmthbf8HQkajUP5ziC8YUA==
      filters: stat,wall,config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJyn3W9t4wpqywCymcIKdwVqh4NtAOw5ySjojDYVbTJR0D3OUTBhRZLukxayt7icGS7T6/7kPUEGxq8ACWCRpwsCAwEAAQ==
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
          url-pattern: "/druid/*"
          # IP白名单(没有配置或者为空，则允许所有访问)
          allow:
          # IP黑名单 (存在共同时，deny优先于allow)
          deny:
          #  禁用HTML页面上的“Reset All”功能
          reset-enable: false
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
