server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://blog.db:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: WDMEWPOCF40ZqPm38BylKDyJG38O57gMucoJAKROQFV9IahSyFQ0iY7Ig7eM/y3bcJ7c1YYvorZeQB9RhPFHCQ==
      filters: stat,wall,config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIGd/rQnd6rx33TAHTOO9355JnBgGYVITFyPkI+064oJRFoqcP1kYuMT2ov8ZDN4p8CznvZdEItl0aZJmHlN0FkCAwEAAQ==
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
          url-pattern: "/druid/*"
          # IP白名单(没有配置或者为空，则允许所有访问)
          allow:
          # IP黑名单 (存在共同时，deny优先于allow)
          deny:
          #  禁用HTML页面上的“Reset All”功能
          reset-enable: false
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

